import type { ContentPack } from '@tss/schema'

export function makeBaseInteractionPack(): ContentPack {
  return {
    gameTitle: 'Test Story',
    packId: 'test_pack',
    version: '0.0.0',
    schemaVersion: '2.0.0',
    world: {
      id: 'world_test',
      name: 'Test World',
      summary: 'A compact runtime test world.',
      editorBackground: 'Runtime test background.',
      playerIntroduction: 'Runtime test introduction.',
      maxDays: 3,
      segments: ['morning', 'noon', 'night'],
      actionPointsPerSegment: 3,
    },
    variables: [
      {
        key: 'rapport',
        name: 'Rapport',
        description: 'Runtime test variable.',
        initialValue: 0,
        min: 0,
        max: 100,
      },
    ],
    maps: [
      {
        id: 'map_test',
        name: 'Test Map',
        width: 1,
        height: 1,
        tiles: [
          {
            id: 'tile_test',
            name: 'Test Tile',
            x: 0,
            y: 0,
            terrain: 'town',
            locationId: 'loc_test',
            buildingIds: [],
            npcIds: ['npc_test'],
            eventIds: [],
            discovered: true,
            visible: true,
            blocked: false,
            dangerLevel: 0,
          },
        ],
      },
    ],
    locations: [
      {
        id: 'loc_test',
        name: 'Test Location',
        type: 'test',
        tags: [],
        state: { discovered: true, is_accessible: true },
        descriptions: {
          default: 'A runtime test location.',
          morning: 'A runtime test location.',
          noon: 'A runtime test location.',
          night: 'A runtime test location.',
        },
        buildingIds: [],
        interactionIds: ['interaction_search_test'],
      },
    ],
    buildings: [],
    factions: [
      {
        id: 'faction_test',
        name: 'Test Faction',
        description: 'A runtime test faction.',
        stanceToPlayer: 0,
      },
    ],
    identities: [
      {
        id: 'identity_test',
        name: 'Test Identity',
        description: 'A runtime test identity.',
        backgroundSummary: 'Runtime test background.',
        intro: {
          title: 'Runtime Test',
          story: 'A runtime test story.',
          origin: 'A runtime test origin.',
          motivation: 'A runtime test motivation.',
        },
        initialState: {
          health: 100,
          stamina: 100,
          money: 0,
          reputation: 0,
          combat: 10,
          negotiation: 0,
          medicine: 0,
          stealth: 0,
        },
        advantages: [],
        disadvantages: [],
      },
    ],
    npcs: [
      {
        id: 'npc_test',
        name: 'Test NPC',
        age: 30,
        identity: 'Tester',
        tier: 'ordinary',
        faction: 'faction_test',
        location: 'loc_test',
        personality: {
          kindness: 0,
          courage: 0,
          greed: 0,
          loyalty: 0,
          suspicion: 0,
          responsibility: 0,
        },
        state: {},
        goals: [],
        secrets: [],
        relationships: [],
        schedule: [],
        behaviorRules: [],
        interactionIds: [],
      },
    ],
    relationships: [],
    interactions: [
      {
        id: 'interaction_search_test',
        name: 'Search Test',
        description: 'Search the runtime test location.',
        type: 'environment',
        targetType: 'location',
        targetId: 'loc_test',
        environmentType: 'search',
      },
    ],
    quests: [
      {
        id: 'quest_search_test',
        title: 'Search Test Quest',
        description: 'Complete by searching the test location.',
        sourceNpcId: 'npc_test',
        completion: {
          type: 'environment',
          environmentType: 'search',
          targetType: 'location',
          targetId: 'loc_test',
          interactionId: 'interaction_search_test',
        },
        rewardIds: ['reward_rapport_test'],
      },
    ],
    rewards: [
      {
        id: 'reward_rapport_test',
        name: 'Rapport Reward',
        description: 'Raises rapport for runtime assertions.',
        effects: [{ type: 'change_variable', key: 'rapport', delta: 5 }],
      },
    ],
    events: [],
    conversations: [],
    items: [],
    endings: [
      {
        id: 'ending_test',
        name: 'Test Ending',
        priority: 1,
        conditions: { fact: 'never', exists: true },
        summary: 'A runtime test ending.',
        causalChainRules: [],
      },
    ],
    runtime: {
      initialState: {
        playerLocationId: 'loc_test',
        selectedTileId: 'tile_test',
        facts: {},
      },
      dailyDriftRules: [],
    },
  }
}
