import { EFFECT_TYPES, ENVIRONMENT_INTERACTION_TYPES, EVENT_TYPES, INTERACTION_TYPES, TERRAIN_TYPES, TIME_SEGMENTS } from '@tss/schema'
import type { TemplateCategory } from './types'

export const templateCategories: TemplateCategory[] = [
  {
    id: 'project',
    name: '项目与世界',
    description: '定义故事包身份、世界时间规则和全局运行尺度。',
    fields: [
      { name: 'packId', type: 'string', required: true, description: '内容包唯一标识，存档和校验按它绑定。', example: 'sample_story' },
      { name: 'world.id', type: 'string', required: true, description: '世界设定唯一标识，可被工具链追踪。', example: 'world_sample' },
      { name: 'world.name', type: 'string', required: true, description: '运行端标题、编辑器、日志和模拟摘要中的世界名称。', example: '示例世界' },
      { name: 'world.summary', type: 'string', required: true, description: '帮助生成器理解题材、冲突和边界。', example: '围绕核心冲突展开的多日调查。' },
      { name: 'world.editorBackground', type: 'string', required: true, description: '给故事编辑者和生成器看的完整世界背景、规则和边界。', example: '示例世界的时间范围、地点边界、势力结构和禁止突破的设定。' },
      { name: 'world.maxDays', type: 'number', required: true, description: '控制模拟最长天数和结局检查窗口。', example: '14' },
      { name: 'world.segments', type: 'TimeSegment[]', required: true, description: '决定每天可行动时段。', example: 'morning, noon, night' },
      { name: 'world.actionPointsPerSegment', type: 'number', required: true, description: '决定每个时段可执行多少行动。', example: '3' },
    ],
    allowedValues: [{ label: 'TimeSegment', values: TIME_SEGMENTS }],
  },
  {
    id: 'variables',
    name: '世界变量',
    description: '描述世界状态的可量化参数，是事件、行为和结局的主要因果桥梁。',
    fields: [
      { name: 'key', type: 'string', required: true, description: '条件和效果通过 variables.<key> 读取它。', example: 'clue_progress' },
      { name: 'name', type: 'string', required: true, description: '编辑器里展示的人类可读名称。', example: '线索进度' },
      { name: 'description', type: 'string', required: true, description: '说明变量影响哪些系统和剧情线。', example: '影响真相事件和调查结局。' },
      { name: 'initialValue', type: 'number', required: true, description: '创建新存档时的初始数值。', example: '15' },
      { name: 'min', type: 'number', required: false, description: '用于进度条归一化和设计边界。', example: '0' },
      { name: 'max', type: 'number', required: false, description: '用于进度条归一化和结局阈值。', example: '100' },
    ],
  },
  {
    id: 'map',
    name: '地图与地块',
    description: '地图由地块组成，地块负责承载地点、建筑、NPC、事件和可见性。',
    fields: [
      { name: 'maps[].id', type: 'string', required: true, description: '地图唯一标识。', example: 'map_city_center' },
      { name: 'maps[].width / height', type: 'number', required: true, description: '决定网格渲染尺寸。', example: '4 / 3' },
      { name: 'tiles[].id', type: 'string', required: true, description: '地块唯一标识，可被 set_tile_visible 引用。', example: 'tile_03_02' },
      { name: 'tiles[].x / y', type: 'number', required: true, description: '决定地块在网格中的位置。', example: '3 / 2' },
      { name: 'tiles[].terrain', type: 'TerrainType', required: true, description: '影响地图颜色、移动成本和题材表达。', example: 'town' },
      { name: 'tiles[].locationId', type: 'string', required: false, description: '绑定地点详情；没有绑定时只是普通地块。', example: 'loc_archive' },
      { name: 'tiles[].buildingIds', type: 'string[]', required: true, description: '用于快速查看地块内建筑。', example: 'building_archive_room' },
      { name: 'tiles[].npcIds', type: 'string[]', required: true, description: '用于地图层展示当前常驻 NPC。', example: 'npc_archivist' },
      { name: 'tiles[].eventIds', type: 'string[]', required: true, description: '提示该地块可能触发哪些事件。', example: 'event_archive_gap' },
      { name: 'tiles[].visible', type: 'boolean', required: true, description: '控制地块是否显示。', example: 'true' },
      { name: 'tiles[].discovered', type: 'boolean', required: true, description: '控制玩家是否已发现地块。', example: 'false' },
      { name: 'tiles[].blocked', type: 'boolean', required: true, description: '控制路径和进入限制。', example: 'false' },
      { name: 'tiles[].dangerLevel', type: 'number', required: true, description: '用于 UI 风险提示和事件设计。', example: '35' },
    ],
    allowedValues: [{ label: 'TerrainType', values: TERRAIN_TYPES }],
  },
  {
    id: 'locations',
    name: '地点与建筑',
    description: '地点负责叙事描述和交互入口，建筑用于承载更细的交互对象。',
    fields: [
      { name: 'locations[].id', type: 'string', required: true, description: '交互、事件、NPC 和运行时状态都可引用地点。', example: 'loc_archive' },
      { name: 'locations[].type', type: 'string', required: true, description: '用于内容分类和编辑器筛选。', example: 'archive' },
      { name: 'locations[].tags', type: 'string[]', required: true, description: '帮助生成器选择题材、支线和风险。', example: '资料, 主线' },
      { name: 'locations[].state', type: 'object', required: true, description: '地点运行时状态，可被 change_location_state 修改。', example: '{ discovered: true, is_accessible: true }' },
      { name: 'locations[].descriptions', type: 'Record<segment,string>', required: true, description: '按时段显示不同环境描述。', example: '{ morning: "...", night: "..." }' },
      { name: 'locations[].buildingIds', type: 'string[]', required: true, description: '绑定地点内建筑。', example: 'building_archive_room' },
      { name: 'locations[].interactionIds', type: 'string[]', required: true, description: '说明该地点可触发哪些交互。', example: 'interaction_search_archive' },
      { name: 'buildings[].interactionIds', type: 'string[]', required: true, description: '说明该建筑可触发哪些交互。', example: 'interaction_open_archive' },
      { name: 'buildings[].state', type: 'object', required: true, description: '建筑自身状态，可被交互和事件修改。', example: '{ unlocked: true }' },
    ],
  },
  {
    id: 'npc',
    name: 'NPC',
    description: 'NPC 是剧情互动、行为规则、关系网络和会话的核心对象。',
    fields: [
      { name: 'id', type: 'string', required: true, description: '事件参与者、会话 speaker、关系目标都引用它。', example: 'npc_archivist' },
      { name: 'name', type: 'string', required: true, description: '编辑器、会话和运行日志展示名称。', example: '档案管理员' },
      { name: 'tier', type: 'core | important | ordinary', required: true, description: '影响内容缺口检查和编辑优先级。', example: 'core' },
      { name: 'faction', type: 'string', required: true, description: '绑定势力，影响关系默认值和阵营设计。', example: 'faction_city_office' },
      { name: 'location', type: 'string', required: true, description: 'NPC 初始所在地。', example: 'loc_archive' },
      { name: 'personality', type: 'Personality', required: true, description: '用于行为规则、生成器和角色一致性。', example: 'kindness: 40, suspicion: 55' },
      { name: 'state', type: 'object', required: true, description: 'NPC 运行时状态，可被 change_npc_state 修改。', example: '{ access_granted: false }' },
      { name: 'goals', type: 'string[]', required: true, description: '定义自主行动和剧情选择依据。', example: '保护档案馆名誉' },
      { name: 'secrets', type: 'Secret[]', required: true, description: '用于秘密揭示、会话和真相线。', example: 'secret_missing_pages' },
      { name: 'relationships', type: 'NpcRelationshipDefinition[]', required: true, description: '定义 NPC 之间的初始关系。', example: 'targetId, value, relationType' },
      { name: 'behaviorRules', type: 'BehaviorRule[]', required: true, description: '让 NPC 根据条件自动改变世界。', example: '压力降低后开放档案' },
      { name: 'background', type: 'object', required: false, description: '拆分公开、私下和隐藏故事。', example: 'publicStory / privateStory / hiddenStory' },
    ],
  },
  {
    id: 'events',
    name: '事件、交互、任务与会话',
    description: '事件负责世界状态变化，交互负责玩家主动操作，任务负责目标、完成方式和奖励。',
    fields: [
      { name: 'events[].type', type: 'EventType', required: true, description: '决定事件归类和设计意图。', example: 'location_event' },
      { name: 'events[].locationId', type: 'string', required: false, description: '限制事件发生地点。', example: 'loc_station' },
      { name: 'events[].participantIds', type: 'string[]', required: true, description: '绑定参与 NPC。', example: 'npc_witness' },
      { name: 'events[].trigger', type: 'ConditionGroup', required: true, description: '决定事件何时触发。', example: '{ fact: "story_started", equals: true }' },
      { name: 'events[].effects', type: 'Effect[]', required: true, description: '事件触发时改变变量、事实、关系或位置。', example: 'change_variable' },
      { name: 'interactions[].id', type: 'string', required: true, description: '交互唯一标识。', example: 'interaction_search_archive' },
      { name: 'interactions[].type', type: 'InteractionType', required: true, description: '决定玩家通过对话、给予、战斗或环境互动推进内容。', example: 'environment' },
      { name: 'interactions[].environmentType', type: 'EnvironmentInteractionType', required: false, description: '环境互动的采集或搜索类型。', example: 'search' },
      { name: 'interactions[].targetType / targetId', type: 'InteractionTargetType / string', required: true, description: '绑定 NPC、地点、建筑或地块。', example: 'location / loc_archive' },
      { name: 'interactions[].cost', type: 'ActionCost', required: false, description: '消耗行动点、体力、金钱或物品。', example: 'actionPoints: 1' },
      { name: 'quests[].sourceNpcId', type: 'string', required: true, description: '任务来源 NPC。', example: 'npc_archivist' },
      { name: 'quests[].completion', type: 'QuestCompletion', required: true, description: '结构化定义任务完成方式。', example: 'environment search loc_archive' },
      { name: 'quests[].rewardIds', type: 'string[]', required: true, description: '绑定任务完成后发放的奖励。', example: 'reward_archive_trust' },
      { name: 'rewards[].effects', type: 'Effect[]', required: true, description: '任务完成后由引擎发放的结构化奖励。', example: 'change_relationship' },
      { name: 'conversations[].id', type: 'string', required: true, description: '会话唯一标识，可被 start_conversation 引用。', example: 'conversation_archivist_first' },
      { name: 'conversations[].npcId', type: 'string', required: true, description: '绑定可发起该会话的 NPC。', example: 'npc_archivist' },
      { name: 'conversations[].title', type: 'string', required: true, description: '玩家在话题列表中看到的标题。', example: '询问缺失记录' },
      { name: 'conversations[].entryNodeId', type: 'string', required: true, description: '进入会话时显示的节点。', example: 'node_entry' },
      { name: 'conversations[].nodes[].speaker', type: 'player | npcId', required: true, description: '控制当前节点由谁发言。', example: 'npc_archivist' },
      { name: 'conversations[].nodes[].replies[].text', type: 'string', required: true, description: '玩家可点击的回复文本。', example: '继续追问' },
      { name: 'conversations[].nodes[].replies[].nextNodeId', type: 'string', required: false, description: '将会话推进到同一会话内的目标节点。', example: 'node_detail' },
      { name: 'conversations[].nodes[].replies[].endConversation', type: 'boolean', required: false, description: '没有下一节点时结束会话。', example: 'true' },
    ],
    allowedValues: [
      { label: 'EventType', values: EVENT_TYPES },
      { label: 'InteractionType', values: INTERACTION_TYPES },
      { label: 'EnvironmentInteractionType', values: ENVIRONMENT_INTERACTION_TYPES },
    ],
  },
  {
    id: 'logic',
    name: '条件、效果与运行时',
    description: '条件读取事实和变量，效果改变世界状态；运行时配置决定初始状态和每日漂移。',
    fields: [
      { name: 'Condition.fact', type: 'string', required: true, description: '支持读取 facts、variables、player、locations、npcs 等路径。', example: 'variables.clue_progress' },
      { name: 'Condition.equals', type: 'unknown', required: false, description: '精确匹配事实值。', example: 'true' },
      { name: 'Condition.greater_than_or_equal', type: 'number', required: false, description: '数值阈值判断。', example: '70' },
      { name: 'Condition.all / any / not', type: 'Condition[]', required: false, description: '组合复杂触发条件。', example: 'all: [{...}, {...}]' },
      { name: 'Effect.type', type: 'EffectType', required: true, description: '决定效果写入哪类运行时状态。', example: 'change_variable' },
      { name: 'runtime.initialState.playerLocationId', type: 'string', required: true, description: '新游戏的初始地点。', example: 'loc_station' },
      { name: 'runtime.initialState.facts', type: 'Record<string,unknown>', required: true, description: '为开场事件和初始条件提供事实。', example: '{ story_started: true }' },
      { name: 'runtime.dailyDriftRules', type: 'DailyDriftRule[]', required: true, description: '每天自动推进变量和世界状态。', example: '传言扩散' },
    ],
    allowedValues: [{ label: 'EffectType', values: EFFECT_TYPES }],
  },
]
